/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/9.0.0/samples
 */

plugins {
    java
    application
}

repositories {
    mavenCentral()
}

java {

    toolchain {
        languageVersion.set(org.gradle.jvm.toolchain.JavaLanguageVersion.of(24))
    }
}

application {
    mainClass.set("com.example.bookbuddy.App")
}

dependencies {
    // JPA/Hibernate
    implementation("org.hibernate.orm:hibernate-core:6.5.2.Final")
    implementation("jakarta.persistence:jakarta.persistence-api:3.1.0")
    implementation("com.zaxxer:HikariCP:5.1.0")

    // PostgreSQL JDBC
    implementation("org.postgresql:postgresql:42.7.7")
}

tasks.jar {
    manifest {
        attributes["Main-Class"] = application.mainClass.get()
    }
}
